// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.25.0
// source: logic_gim_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicMetaType int32

const (
	TopicMetaType_TopicMetaType_Unknown TopicMetaType = 0
	TopicMetaType_TopicMetaType_Single  TopicMetaType = 1
	TopicMetaType_TopicMetaType_Group   TopicMetaType = 2
)

// Enum value maps for TopicMetaType.
var (
	TopicMetaType_name = map[int32]string{
		0: "TopicMetaType_Unknown",
		1: "TopicMetaType_Single",
		2: "TopicMetaType_Group",
	}
	TopicMetaType_value = map[string]int32{
		"TopicMetaType_Unknown": 0,
		"TopicMetaType_Single":  1,
		"TopicMetaType_Group":   2,
	}
)

func (x TopicMetaType) Enum() *TopicMetaType {
	p := new(TopicMetaType)
	*p = x
	return p
}

func (x TopicMetaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopicMetaType) Descriptor() protoreflect.EnumDescriptor {
	return file_logic_gim_message_proto_enumTypes[0].Descriptor()
}

func (TopicMetaType) Type() protoreflect.EnumType {
	return &file_logic_gim_message_proto_enumTypes[0]
}

func (x TopicMetaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopicMetaType.Descriptor instead.
func (TopicMetaType) EnumDescriptor() ([]byte, []int) {
	return file_logic_gim_message_proto_rawDescGZIP(), []int{0}
}

type ContentType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//
	//	*ContentType_Text
	//	*ContentType_Link
	//	*ContentType_Image
	//	*ContentType_Document
	//	*ContentType_Video
	Content isContentType_Content `protobuf_oneof:"content"`
}

func (x *ContentType) Reset() {
	*x = ContentType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_gim_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentType) ProtoMessage() {}

func (x *ContentType) ProtoReflect() protoreflect.Message {
	mi := &file_logic_gim_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentType.ProtoReflect.Descriptor instead.
func (*ContentType) Descriptor() ([]byte, []int) {
	return file_logic_gim_message_proto_rawDescGZIP(), []int{0}
}

func (m *ContentType) GetContent() isContentType_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *ContentType) GetText() *ContentText {
	if x, ok := x.GetContent().(*ContentType_Text); ok {
		return x.Text
	}
	return nil
}

func (x *ContentType) GetLink() *ContentLink {
	if x, ok := x.GetContent().(*ContentType_Link); ok {
		return x.Link
	}
	return nil
}

func (x *ContentType) GetImage() *ContentImage {
	if x, ok := x.GetContent().(*ContentType_Image); ok {
		return x.Image
	}
	return nil
}

func (x *ContentType) GetDocument() *ContentDocument {
	if x, ok := x.GetContent().(*ContentType_Document); ok {
		return x.Document
	}
	return nil
}

func (x *ContentType) GetVideo() *ContentVideo {
	if x, ok := x.GetContent().(*ContentType_Video); ok {
		return x.Video
	}
	return nil
}

type isContentType_Content interface {
	isContentType_Content()
}

type ContentType_Text struct {
	Text *ContentText `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type ContentType_Link struct {
	Link *ContentLink `protobuf:"bytes,2,opt,name=link,proto3,oneof"`
}

type ContentType_Image struct {
	Image *ContentImage `protobuf:"bytes,3,opt,name=image,proto3,oneof"`
}

type ContentType_Document struct {
	Document *ContentDocument `protobuf:"bytes,4,opt,name=document,proto3,oneof"`
}

type ContentType_Video struct {
	Video *ContentVideo `protobuf:"bytes,5,opt,name=video,proto3,oneof"`
}

func (*ContentType_Text) isContentType_Content() {}

func (*ContentType_Link) isContentType_Content() {}

func (*ContentType_Image) isContentType_Content() {}

func (*ContentType_Document) isContentType_Content() {}

func (*ContentType_Video) isContentType_Content() {}

type ContentText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ContentText) Reset() {
	*x = ContentText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_gim_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentText) ProtoMessage() {}

func (x *ContentText) ProtoReflect() protoreflect.Message {
	mi := &file_logic_gim_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentText.ProtoReflect.Descriptor instead.
func (*ContentText) Descriptor() ([]byte, []int) {
	return file_logic_gim_message_proto_rawDescGZIP(), []int{1}
}

func (x *ContentText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ContentLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ContentLink) Reset() {
	*x = ContentLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_gim_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentLink) ProtoMessage() {}

func (x *ContentLink) ProtoReflect() protoreflect.Message {
	mi := &file_logic_gim_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentLink.ProtoReflect.Descriptor instead.
func (*ContentLink) Descriptor() ([]byte, []int) {
	return file_logic_gim_message_proto_rawDescGZIP(), []int{2}
}

func (x *ContentLink) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *ContentLink) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ContentImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ThumbUrl    string `protobuf:"bytes,2,opt,name=thumb_url,json=thumbUrl,proto3" json:"thumb_url,omitempty"`
	ResourceUrl string `protobuf:"bytes,3,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	FileHash    string `protobuf:"bytes,4,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	FileStatus  int32  `protobuf:"varint,5,opt,name=file_status,json=fileStatus,proto3" json:"file_status,omitempty"`
}

func (x *ContentImage) Reset() {
	*x = ContentImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_gim_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentImage) ProtoMessage() {}

func (x *ContentImage) ProtoReflect() protoreflect.Message {
	mi := &file_logic_gim_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentImage.ProtoReflect.Descriptor instead.
func (*ContentImage) Descriptor() ([]byte, []int) {
	return file_logic_gim_message_proto_rawDescGZIP(), []int{3}
}

func (x *ContentImage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContentImage) GetThumbUrl() string {
	if x != nil {
		return x.ThumbUrl
	}
	return ""
}

func (x *ContentImage) GetResourceUrl() string {
	if x != nil {
		return x.ResourceUrl
	}
	return ""
}

func (x *ContentImage) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *ContentImage) GetFileStatus() int32 {
	if x != nil {
		return x.FileStatus
	}
	return 0
}

type ContentDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ResourceUrl string `protobuf:"bytes,2,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	FileHash    string `protobuf:"bytes,3,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	FileStatus  int32  `protobuf:"varint,5,opt,name=file_status,json=fileStatus,proto3" json:"file_status,omitempty"`
}

func (x *ContentDocument) Reset() {
	*x = ContentDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_gim_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentDocument) ProtoMessage() {}

func (x *ContentDocument) ProtoReflect() protoreflect.Message {
	mi := &file_logic_gim_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentDocument.ProtoReflect.Descriptor instead.
func (*ContentDocument) Descriptor() ([]byte, []int) {
	return file_logic_gim_message_proto_rawDescGZIP(), []int{4}
}

func (x *ContentDocument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContentDocument) GetResourceUrl() string {
	if x != nil {
		return x.ResourceUrl
	}
	return ""
}

func (x *ContentDocument) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *ContentDocument) GetFileStatus() int32 {
	if x != nil {
		return x.FileStatus
	}
	return 0
}

type ContentVideo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ResourceUrl string `protobuf:"bytes,2,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	FileHash    string `protobuf:"bytes,3,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	FileStatus  int32  `protobuf:"varint,5,opt,name=file_status,json=fileStatus,proto3" json:"file_status,omitempty"`
}

func (x *ContentVideo) Reset() {
	*x = ContentVideo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_gim_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentVideo) ProtoMessage() {}

func (x *ContentVideo) ProtoReflect() protoreflect.Message {
	mi := &file_logic_gim_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentVideo.ProtoReflect.Descriptor instead.
func (*ContentVideo) Descriptor() ([]byte, []int) {
	return file_logic_gim_message_proto_rawDescGZIP(), []int{5}
}

func (x *ContentVideo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContentVideo) GetResourceUrl() string {
	if x != nil {
		return x.ResourceUrl
	}
	return ""
}

func (x *ContentVideo) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *ContentVideo) GetFileStatus() int32 {
	if x != nil {
		return x.FileStatus
	}
	return 0
}

type Content struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content *ContentType `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Content) Reset() {
	*x = Content{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_gim_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_logic_gim_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_logic_gim_message_proto_rawDescGZIP(), []int{6}
}

func (x *Content) GetContent() *ContentType {
	if x != nil {
		return x.Content
	}
	return nil
}

type TopicMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetaType TopicMetaType `protobuf:"varint,1,opt,name=meta_type,json=metaType,proto3,enum=pb.TopicMetaType" json:"meta_type,omitempty"`
	MetaId   *TopicMetaId  `protobuf:"bytes,2,opt,name=meta_id,json=metaId,proto3" json:"meta_id,omitempty"`
}

func (x *TopicMeta) Reset() {
	*x = TopicMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_gim_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicMeta) ProtoMessage() {}

func (x *TopicMeta) ProtoReflect() protoreflect.Message {
	mi := &file_logic_gim_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicMeta.ProtoReflect.Descriptor instead.
func (*TopicMeta) Descriptor() ([]byte, []int) {
	return file_logic_gim_message_proto_rawDescGZIP(), []int{7}
}

func (x *TopicMeta) GetMetaType() TopicMetaType {
	if x != nil {
		return x.MetaType
	}
	return TopicMetaType_TopicMetaType_Unknown
}

func (x *TopicMeta) GetMetaId() *TopicMetaId {
	if x != nil {
		return x.MetaId
	}
	return nil
}

type TopicMetaId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId    string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SenderId   string `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId string `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
}

func (x *TopicMetaId) Reset() {
	*x = TopicMetaId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_gim_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicMetaId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicMetaId) ProtoMessage() {}

func (x *TopicMetaId) ProtoReflect() protoreflect.Message {
	mi := &file_logic_gim_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicMetaId.ProtoReflect.Descriptor instead.
func (*TopicMetaId) Descriptor() ([]byte, []int) {
	return file_logic_gim_message_proto_rawDescGZIP(), []int{8}
}

func (x *TopicMetaId) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *TopicMetaId) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *TopicMetaId) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

type GimMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountSn   string       `protobuf:"bytes,1,opt,name=account_sn,json=accountSn,proto3" json:"account_sn,omitempty"`         // Social account, the user id and the following account_id are the same
	TopicMeta   *TopicMeta   `protobuf:"bytes,2,opt,name=topic_meta,json=topicMeta,proto3" json:"topic_meta,omitempty"`         // Message identifier metadata message
	ContentType *ContentType `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`   // Message content type
	Content     *Content     `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                              // Message content
	SocialMsgId string       `protobuf:"bytes,5,opt,name=social_msg_id,json=socialMsgId,proto3" json:"social_msg_id,omitempty"` // Social software service msg id
	MsgId       string       `protobuf:"bytes,6,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                     // Internal message id
	SendTime    int64        `protobuf:"varint,7,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`           // Message send time in milliseconds
	AccountId   string       `protobuf:"bytes,8,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`         // Social account id in the social platform, which may be changed to a phone number (if the account is unregistered and then re-registered) and cannot uniquely identify the identifier of the social platform; if it is determined to be different, it can also be set to the same as account_sn
}

func (x *GimMessage) Reset() {
	*x = GimMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_gim_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GimMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GimMessage) ProtoMessage() {}

func (x *GimMessage) ProtoReflect() protoreflect.Message {
	mi := &file_logic_gim_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GimMessage.ProtoReflect.Descriptor instead.
func (*GimMessage) Descriptor() ([]byte, []int) {
	return file_logic_gim_message_proto_rawDescGZIP(), []int{9}
}

func (x *GimMessage) GetAccountSn() string {
	if x != nil {
		return x.AccountSn
	}
	return ""
}

func (x *GimMessage) GetTopicMeta() *TopicMeta {
	if x != nil {
		return x.TopicMeta
	}
	return nil
}

func (x *GimMessage) GetContentType() *ContentType {
	if x != nil {
		return x.ContentType
	}
	return nil
}

func (x *GimMessage) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GimMessage) GetSocialMsgId() string {
	if x != nil {
		return x.SocialMsgId
	}
	return ""
}

func (x *GimMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *GimMessage) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *GimMessage) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

var File_logic_gim_message_proto protoreflect.FileDescriptor

var file_logic_gim_message_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x5f, 0x67, 0x69, 0x6d, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xed, 0x01,
	0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4c,
	0x69, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x28, 0x0a, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x08,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x21, 0x0a,
	0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x22, 0x35, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0xa0, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x74, 0x68, 0x75, 0x6d, 0x62, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x66, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x0f, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66,
	0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x34, 0x0a, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0x65, 0x0a, 0x09, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x09,
	0x6d, 0x65, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x07,
	0x6d, 0x65, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x49, 0x64, 0x52, 0x06,
	0x6d, 0x65, 0x74, 0x61, 0x49, 0x64, 0x22, 0x66, 0x0a, 0x0b, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d,
	0x65, 0x74, 0x61, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0xab,
	0x02, 0x0a, 0x0a, 0x47, 0x69, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x6e, 0x12, 0x2c, 0x0a, 0x0a,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x09, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x0c, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f,
	0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x6f,
	0x63, 0x69, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x2a, 0x5d, 0x0a, 0x0d,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a,
	0x15, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x55,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x4d, 0x65, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x5f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x10, 0x02, 0x42, 0x15, 0x5a, 0x13, 0x67,
	0x69, 0x6d, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_logic_gim_message_proto_rawDescOnce sync.Once
	file_logic_gim_message_proto_rawDescData = file_logic_gim_message_proto_rawDesc
)

func file_logic_gim_message_proto_rawDescGZIP() []byte {
	file_logic_gim_message_proto_rawDescOnce.Do(func() {
		file_logic_gim_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_logic_gim_message_proto_rawDescData)
	})
	return file_logic_gim_message_proto_rawDescData
}

var file_logic_gim_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_logic_gim_message_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_logic_gim_message_proto_goTypes = []interface{}{
	(TopicMetaType)(0),      // 0: pb.TopicMetaType
	(*ContentType)(nil),     // 1: pb.ContentType
	(*ContentText)(nil),     // 2: pb.ContentText
	(*ContentLink)(nil),     // 3: pb.ContentLink
	(*ContentImage)(nil),    // 4: pb.ContentImage
	(*ContentDocument)(nil), // 5: pb.ContentDocument
	(*ContentVideo)(nil),    // 6: pb.ContentVideo
	(*Content)(nil),         // 7: pb.Content
	(*TopicMeta)(nil),       // 8: pb.TopicMeta
	(*TopicMetaId)(nil),     // 9: pb.TopicMetaId
	(*GimMessage)(nil),      // 10: pb.GimMessage
}
var file_logic_gim_message_proto_depIdxs = []int32{
	2,  // 0: pb.ContentType.text:type_name -> pb.ContentText
	3,  // 1: pb.ContentType.link:type_name -> pb.ContentLink
	4,  // 2: pb.ContentType.image:type_name -> pb.ContentImage
	5,  // 3: pb.ContentType.document:type_name -> pb.ContentDocument
	6,  // 4: pb.ContentType.video:type_name -> pb.ContentVideo
	1,  // 5: pb.Content.content:type_name -> pb.ContentType
	0,  // 6: pb.TopicMeta.meta_type:type_name -> pb.TopicMetaType
	9,  // 7: pb.TopicMeta.meta_id:type_name -> pb.TopicMetaId
	8,  // 8: pb.GimMessage.topic_meta:type_name -> pb.TopicMeta
	1,  // 9: pb.GimMessage.content_type:type_name -> pb.ContentType
	7,  // 10: pb.GimMessage.content:type_name -> pb.Content
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_logic_gim_message_proto_init() }
func file_logic_gim_message_proto_init() {
	if File_logic_gim_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logic_gim_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_gim_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_gim_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_gim_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_gim_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_gim_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentVideo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_gim_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Content); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_gim_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_gim_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicMetaId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_gim_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GimMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_logic_gim_message_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ContentType_Text)(nil),
		(*ContentType_Link)(nil),
		(*ContentType_Image)(nil),
		(*ContentType_Document)(nil),
		(*ContentType_Video)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logic_gim_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logic_gim_message_proto_goTypes,
		DependencyIndexes: file_logic_gim_message_proto_depIdxs,
		EnumInfos:         file_logic_gim_message_proto_enumTypes,
		MessageInfos:      file_logic_gim_message_proto_msgTypes,
	}.Build()
	File_logic_gim_message_proto = out.File
	file_logic_gim_message_proto_rawDesc = nil
	file_logic_gim_message_proto_goTypes = nil
	file_logic_gim_message_proto_depIdxs = nil
}
