MySQL = "jhim:Szyw@2023@tcp(172.16.100.101:3306)/gim?charset=utf8mb4&parseTime=true" # mysql address
RedisHost = "172.16.100.101:6379" # redis address
RedisPassword = "" # redis password
ConnectRPCListenHost = "192.168.110.238"
ConnectRPCListenPort = ":40000"
LogicRPCListenHost = "192.168.110.238"
LogicRPCListenPort = ":40010"
BusinessRPCListenHost = "192.168.110.238"
BusinessRPCListenPort = ":40020"
ConnectTCPListenAddr = "0.0.0.0:40001"
